Gegeben a 5 by 5 game
Wenn I toggle the cell at (2, 3)
Dann the grid should look like
.....
.....
.....
..X..
.....
Wenn I toggle the cell at (2, 4)
Dann the grid should look like
.....
.....
.....
..X..
..X..
Wenn I toggle the cell at (2, 3)
Dann the grid should look like
.....
.....
.....
.....
..X..
